md data
wget -P data --no-check-certificate http://kursbuch.bahn.de/hafas-res/img/kbview/karten/sk-0-0.jpg
wget -P data --no-check-certificate http://kursbuch.bahn.de/hafas-res/img/kbview/karten/sk-0-1.jpg
wget -P data --no-check-certificate http://kursbuch.bahn.de/hafas-res/img/kbview/karten/sk-0-2.jpg
wget -P data --no-check-certificate http://kursbuch.bahn.de/hafas-res/img/kbview/karten/sk-0-3.jpg
wget -P data --no-check-certificate http://kursbuch.bahn.de/hafas-res/img/kbview/karten/sk-0-4.jpg
wget -P data --no-check-certificate http://kursbuch.bahn.de/hafas-res/img/kbview/karten/sk-0-5.jpg
wget -P data --no-check-certificate http://kursbuch.bahn.de/hafas-res/img/kbview/karten/sk-0-6.jpg
wget -P data --no-check-certificate http://kursbuch.bahn.de/hafas-res/img/kbview/karten/sk-0-7.jpg
wget -P data --no-check-certificate http://kursbuch.bahn.de/hafas-res/img/kbview/karten/sk-0-8.jpg
wget -P data --no-check-certificate http://kursbuch.bahn.de/hafas-res/img/kbview/karten/sk-0-9.jpg
wget -P data --no-check-certificate http://kursbuch.bahn.de/hafas-res/img/kbview/karten/sk-0-10.jpg
wget -P data --no-check-certificate http://kursbuch.bahn.de/hafas-res/img/kbview/karten/sk-1-0.jpg
wget -P data --no-check-certificate http://kursbuch.bahn.de/hafas-res/img/kbview/karten/sk-1-1.jpg
wget -P data --no-check-certificate http://kursbuch.bahn.de/hafas-res/img/kbview/karten/sk-1-2.jpg
wget -P data --no-check-certificate http://kursbuch.bahn.de/hafas-res/img/kbview/karten/sk-1-3.jpg
wget -P data --no-check-certificate http://kursbuch.bahn.de/hafas-res/img/kbview/karten/sk-1-4.jpg
wget -P data --no-check-certificate http://kursbuch.bahn.de/hafas-res/img/kbview/karten/sk-1-5.jpg
wget -P data --no-check-certificate http://kursbuch.bahn.de/hafas-res/img/kbview/karten/sk-1-6.jpg
wget -P data --no-check-certificate http://kursbuch.bahn.de/hafas-res/img/kbview/karten/sk-1-7.jpg
wget -P data --no-check-certificate http://kursbuch.bahn.de/hafas-res/img/kbview/karten/sk-1-8.jpg
wget -P data --no-check-certificate http://kursbuch.bahn.de/hafas-res/img/kbview/karten/sk-1-9.jpg
wget -P data --no-check-certificate http://kursbuch.bahn.de/hafas-res/img/kbview/karten/sk-1-10.jpg
wget -P data --no-check-certificate http://kursbuch.bahn.de/hafas-res/img/kbview/karten/sk-2-0.jpg
wget -P data --no-check-certificate http://kursbuch.bahn.de/hafas-res/img/kbview/karten/sk-2-1.jpg
wget -P data --no-check-certificate http://kursbuch.bahn.de/hafas-res/img/kbview/karten/sk-2-2.jpg
wget -P data --no-check-certificate http://kursbuch.bahn.de/hafas-res/img/kbview/karten/sk-2-3.jpg
wget -P data --no-check-certificate http://kursbuch.bahn.de/hafas-res/img/kbview/karten/sk-2-4.jpg
wget -P data --no-check-certificate http://kursbuch.bahn.de/hafas-res/img/kbview/karten/sk-2-5.jpg
wget -P data --no-check-certificate http://kursbuch.bahn.de/hafas-res/img/kbview/karten/sk-2-6.jpg
wget -P data --no-check-certificate http://kursbuch.bahn.de/hafas-res/img/kbview/karten/sk-2-7.jpg
wget -P data --no-check-certificate http://kursbuch.bahn.de/hafas-res/img/kbview/karten/sk-2-8.jpg
wget -P data --no-check-certificate http://kursbuch.bahn.de/hafas-res/img/kbview/karten/sk-2-9.jpg
wget -P data --no-check-certificate http://kursbuch.bahn.de/hafas-res/img/kbview/karten/sk-2-10.jpg
wget -P data --no-check-certificate http://kursbuch.bahn.de/hafas-res/img/kbview/karten/sk-3-0.jpg
wget -P data --no-check-certificate http://kursbuch.bahn.de/hafas-res/img/kbview/karten/sk-3-1.jpg
wget -P data --no-check-certificate http://kursbuch.bahn.de/hafas-res/img/kbview/karten/sk-3-2.jpg
wget -P data --no-check-certificate http://kursbuch.bahn.de/hafas-res/img/kbview/karten/sk-3-3.jpg
wget -P data --no-check-certificate http://kursbuch.bahn.de/hafas-res/img/kbview/karten/sk-3-4.jpg
wget -P data --no-check-certificate http://kursbuch.bahn.de/hafas-res/img/kbview/karten/sk-3-5.jpg
wget -P data --no-check-certificate http://kursbuch.bahn.de/hafas-res/img/kbview/karten/sk-3-6.jpg
wget -P data --no-check-certificate http://kursbuch.bahn.de/hafas-res/img/kbview/karten/sk-3-7.jpg
wget -P data --no-check-certificate http://kursbuch.bahn.de/hafas-res/img/kbview/karten/sk-3-8.jpg
wget -P data --no-check-certificate http://kursbuch.bahn.de/hafas-res/img/kbview/karten/sk-3-9.jpg
wget -P data --no-check-certificate http://kursbuch.bahn.de/hafas-res/img/kbview/karten/sk-3-10.jpg
wget -P data --no-check-certificate http://kursbuch.bahn.de/hafas-res/img/kbview/karten/sk-4-0.jpg
wget -P data --no-check-certificate http://kursbuch.bahn.de/hafas-res/img/kbview/karten/sk-4-1.jpg
wget -P data --no-check-certificate http://kursbuch.bahn.de/hafas-res/img/kbview/karten/sk-4-2.jpg
wget -P data --no-check-certificate http://kursbuch.bahn.de/hafas-res/img/kbview/karten/sk-4-3.jpg
wget -P data --no-check-certificate http://kursbuch.bahn.de/hafas-res/img/kbview/karten/sk-4-4.jpg
wget -P data --no-check-certificate http://kursbuch.bahn.de/hafas-res/img/kbview/karten/sk-4-5.jpg
wget -P data --no-check-certificate http://kursbuch.bahn.de/hafas-res/img/kbview/karten/sk-4-6.jpg
wget -P data --no-check-certificate http://kursbuch.bahn.de/hafas-res/img/kbview/karten/sk-4-7.jpg
wget -P data --no-check-certificate http://kursbuch.bahn.de/hafas-res/img/kbview/karten/sk-4-8.jpg
wget -P data --no-check-certificate http://kursbuch.bahn.de/hafas-res/img/kbview/karten/sk-4-9.jpg
wget -P data --no-check-certificate http://kursbuch.bahn.de/hafas-res/img/kbview/karten/sk-4-10.jpg
wget -P data --no-check-certificate http://kursbuch.bahn.de/hafas-res/img/kbview/karten/sk-5-0.jpg
wget -P data --no-check-certificate http://kursbuch.bahn.de/hafas-res/img/kbview/karten/sk-5-1.jpg
wget -P data --no-check-certificate http://kursbuch.bahn.de/hafas-res/img/kbview/karten/sk-5-2.jpg
wget -P data --no-check-certificate http://kursbuch.bahn.de/hafas-res/img/kbview/karten/sk-5-3.jpg
wget -P data --no-check-certificate http://kursbuch.bahn.de/hafas-res/img/kbview/karten/sk-5-4.jpg
wget -P data --no-check-certificate http://kursbuch.bahn.de/hafas-res/img/kbview/karten/sk-5-5.jpg
wget -P data --no-check-certificate http://kursbuch.bahn.de/hafas-res/img/kbview/karten/sk-5-6.jpg
wget -P data --no-check-certificate http://kursbuch.bahn.de/hafas-res/img/kbview/karten/sk-5-7.jpg
wget -P data --no-check-certificate http://kursbuch.bahn.de/hafas-res/img/kbview/karten/sk-5-8.jpg
wget -P data --no-check-certificate http://kursbuch.bahn.de/hafas-res/img/kbview/karten/sk-5-9.jpg
wget -P data --no-check-certificate http://kursbuch.bahn.de/hafas-res/img/kbview/karten/sk-5-10.jpg